"""initial schema

Revision ID: 8264fa3eb267
Revises: 
Create Date: 2026-07-08 15:48:18.836677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8264fa3eb267'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_desc', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cbam_products',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('cn_code', sa.String(length=20), nullable=False),
    sa.Column('description_tr', sa.String(length=255), nullable=False),
    sa.Column('description_en', sa.String(length=255), nullable=False),
    sa.Column('default_emission_factor', sa.Float(), nullable=True),
    sa.Column('eu_benchmark', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=11), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sasb_volume', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_tl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('is_regulated', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_exporter', sa.Boolean(), nullable=False),
    sa.Column('net_zero_target_year', sa.Integer(), nullable=True),
    sa.Column('brand_color', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('theme_settings', sa.JSON(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('standard', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_sections', sa.JSON(), nullable=False),
    sa.Column('regulatory_refs', sa.JSON(), nullable=False),
    sa.Column('prompt_suffix', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('unique_token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_unique_token'), 'suppliers', ['unique_token'], unique=True)
    op.create_table('cbam_declarations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('declaration_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('product_cn_code', sa.String(length=20), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('export_quantity_tonnes', sa.Float(), nullable=False),
    sa.Column('export_destination', sa.String(length=5), nullable=False),
    sa.Column('direct_emissions_tco2e', sa.Float(), nullable=True),
    sa.Column('indirect_emissions_tco2e', sa.Float(), nullable=True),
    sa.Column('total_embedded_emissions', sa.Float(), nullable=True),
    sa.Column('emission_intensity', sa.Float(), nullable=True),
    sa.Column('is_de_minimis', sa.Boolean(), nullable=False),
    sa.Column('carbon_price_paid_local', sa.Float(), nullable=True),
    sa.Column('cbam_certificates_required', sa.Integer(), nullable=True),
    sa.Column('cbam_certificate_cost_eur', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(length=20), nullable=False),
    sa.Column('emission_factor_source', sa.String(length=100), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_scores',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.Column('score_change', sa.Integer(), nullable=True),
    sa.Column('gar_eligible', sa.String(length=20), nullable=True),
    sa.Column('gar_contribution', sa.Float(), nullable=True),
    sa.Column('methodology_version', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('calculated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emission_data',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('reporting_boundary', sa.String(length=30), nullable=False),
    sa.Column('calculation_standard', sa.String(length=30), nullable=False),
    sa.Column('natural_gas_m3', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('diesel_liters', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lpg_kg', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('coal_tons', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('company_vehicles_km', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fugitive_emissions_kg', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('scope1_co2e', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('electricity_kwh', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('electricity_source', sa.String(length=30), nullable=False),
    sa.Column('steam_gj', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('scope2_location_co2e', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('scope2_market_co2e', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('business_travel_flight_km', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('employee_commute_km', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('purchased_goods_spend_tl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('waste_tons', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('water_m3', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('scope3_co2e', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('scope3_breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('activity_metric', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('loan_portfolio_tl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('green_finance_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('financed_emissions_co2e', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('clinker_tons', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cement_production_tons', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('alternative_fuel_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('electricity_generated_mwh', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('renewable_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('earthquake_zone', sa.String(length=50), nullable=True),
    sa.Column('flood_risk', sa.String(length=20), nullable=True),
    sa.Column('drought_risk', sa.String(length=20), nullable=True),
    sa.Column('ndvi_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('managed_company_ids', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('advisory_notes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rule_type', sa.String(length=40), nullable=False),
    sa.Column('standard', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('notify_days_before', sa.Integer(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_connections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_records', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiality_assessments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=20), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('financial_score', sa.Float(), nullable=True),
    sa.Column('stakeholder_count', sa.Integer(), nullable=True),
    sa.Column('stakeholder_groups', sa.JSON(), nullable=True),
    sa.Column('material_topics', sa.JSON(), nullable=True),
    sa.Column('methodology_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emission_data_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('standard', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('compliance_grade', sa.String(length=2), nullable=True),
    sa.Column('compliance_detail', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('word_url', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('assurance_firm', sa.String(length=50), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_of', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['emission_data_id'], ['emission_data.id'], ),
    sa.ForeignKeyConstraint(['version_of'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_chain',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('quantity_tonnes', sa.Float(), nullable=True),
    sa.Column('import_year', sa.Integer(), nullable=True),
    sa.Column('origin_country', sa.String(length=5), nullable=False),
    sa.Column('origin_region', sa.String(length=255), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('geo_polygon', sa.JSON(), nullable=True),
    sa.Column('deforestation_free', sa.Boolean(), nullable=True),
    sa.Column('deforestation_cutoff_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('due_diligence_docs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('eudr_reference_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('auditor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('findings', sa.String(), nullable=True),
    sa.Column('assurance_level', sa.String(), nullable=True),
    sa.Column('materiality_threshold', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['emission_id'], ['emission_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['autopilot_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_drafts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emission_data_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['emission_data_id'], ['emission_data.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('supply_chain_alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('supply_chain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supply_chain_id'], ['supply_chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_chain_alerts')
    op.drop_table('share_links')
    op.drop_table('report_drafts')
    op.drop_table('integration_logs')
    op.drop_table('autopilot_runs')
    op.drop_table('verifications')
    op.drop_table('supply_chain')
    op.drop_table('reports')
    op.drop_table('materiality_assessments')
    op.drop_table('integration_connections')
    op.drop_table('autopilot_rules')
    op.drop_table('advisory_notes')
    op.drop_table('users')
    op.drop_table('emission_data')
    op.drop_table('credit_scores')
    op.drop_table('cbam_declarations')
    op.drop_index(op.f('ix_suppliers_unique_token'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('report_templates')
    op.drop_table('companies')
    op.drop_table('cbam_products')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
